source: docs  # ソースを docs フォルダに設定
destination: _site  # ビルド結果の保存先
baseurl: "/katago-kifu-search"  # 必要に応じて設定

title: "勉強ログ"
description: "勉強の進捗と学びの記録"
theme: minima

# ペルマリンク設定
permalink: "/:year/:month/:day/:title.html"

collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title.html
    dir: docs/_posts  # _posts の場所を docs/_posts に指定

# docs/index.md をトップページに指定
defaults:
  - scope:
      path: "index.md"  # index.md のみ
    values:
      layout: "home"  # トップページ用のレイアウト
      title: "勉強ログ"

  - scope:
      path: ""  # 他のファイルすべて
    values:
      layout: "default"  # 他のページは default レイアウト
