source: docs  # ソースを docs フォルダに設定
destination: _site  # ビルド結果の保存先
baseurl: "/katago-kifu-search"  # 必要に応じて設定

title: "開発ログ"
description: "開発記録"
theme: minima


# ペルマリンク設定
permalink: "/:year/:month/:day/:title.html"

collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title.html
    dir: docs/_posts  # _posts の場所を docs/_posts に指定

defaults:
  - scope:
      path: "" 
    values:
      layout: "default"  # トップページ用のレイアウト
      title: "勉強ログ"
plugins:
  - jekyll-sitemap
